tempestas_mons.web/Controllers/RoadConditionController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tempestas_mons.domain;
using tempestas_mons.domain.models;
using tempestas_mons.domain.services;
using tempestas_mons.web.Models.roadconditions;

namespace tempestas_mons.web.Controllers
{
    public class RoadConditionController : Controller
    {
        private readonly RoadConditionRepository _roadConditionRepository;

        public RoadConditionController():this(new RoadConditionRepository(new StreamReaderFactory()))
        {
            
        }

        public RoadConditionController(RoadConditionRepository roadConditionRepository)
        {
            _roadConditionRepository = roadConditionRepository;
        }

        public ViewResult Index()
        {
            var viewModel = new RoadConditionIndexViewModel
            {
                StartDate = DateTime.Today.ToString(),
                EndDate = DateTime.Today.AddDays(-1).ToString(),
                Summary = new RoadConditionSummaryViewModel
                {
                    PercentChainsRequiredAllVehicles = 0,
                    PercentChainsRequiredExceptAllWheelDrive = 0,
                    PercentPassClosed = 0,
                    PercentTractionTiresAdvised = 0,
                    PercentTractionTiresRequired = 0,
                    PercentTrafficDelayed = 0,
                    PercentTrafficDelayedForAvalancheControl = 0,
                    PercentTrafficStoppedForAvalancheControl = 0,
                }
            };

            return View(viewModel);
        }

        [HttpPost]
        public ViewResult Index(string startDate, string endDate, string direction)
        {
            var start = DateTime.Parse(startDate);
            var end = DateTime.Parse(endDate);

            Direction? trafficDirection = null;
            if (direction != "All")
                trafficDirection = (Direction)Enum.Parse(typeof(Direction), direction);

            var dataInRange = _roadConditionRepository.Get()
                .Where(d => d.Start >= start)
                .Where(d => d.End <= end)
                .SelectMany(d => d.TravelRestrictions);

            if(trafficDirection.HasValue)
                dataInRange = dataInRange.Where(d => d.Direction == trafficDirection);

            var summary = MapSummary(dataInRange);

         
            var viewModel = new RoadConditionIndexViewModel
            {
                StartDate = startDate,
                EndDate = endDate,
                Direction = direction,
                Summary = summary
            };


            return View(viewModel);
        }

        private RoadConditionSummaryViewModel MapSummary(IEnumerable<TravelRestriction> restrictionsInRange)
        {
            var realizedRestrictions = restrictionsInRange.ToList();

            var count = realizedRestrictions.Count;

            var chainsRequiredAllVehiclesCount = realizedRestrictions.Count(r=>r.Restrictions.Contains(Restriction.ChainsRequiredAllVehicles));
            var chainsRequiredExceptAWDCount = realizedRestrictions.Count(r => r.Restrictions.Contains(Restriction.ChainsRequiredExceptAllWheelDrive));
            var passClosedCount = realizedRestrictions.Count(r => r.Restrictions.Contains(Restriction.PassClosed));
            var tractionTiresAdvisedCount = realizedRestrictions.Count(r => r.Restrictions.Contains(Restriction.TractionTiresAdvised));
            var tractionTiresRequiredCount = realizedRestrictions.Count(r => r.Restrictions.Contains(Restriction.TractionTiresRequired));
            var trafficDelayedCount = realizedRestrictions.Count(r => r.Restrictions.Contains(Restriction.TrafficDelayed));
            var trafficDealyedForAvalancheControlCount = realizedRestrictions.Count(r => r.Restrictions.Contains(Restriction.TrafficDelayedForAvalancheControl));
            var trafficStoppedForAvalancheControlCount = realizedRestrictions.Count(r => r.Restrictions.Contains(Restriction.TrafficStoppedForAvalancheControl));

            var roadConditionSummaryViewModel = new RoadConditionSummaryViewModel
            {
                PercentChainsRequiredAllVehicles = Percentage(chainsRequiredAllVehiclesCount,count),
                PercentChainsRequiredExceptAllWheelDrive = Percentage(chainsRequiredExceptAWDCount,count),
                PercentPassClosed = Percentage(passClosedCount,count),
                PercentTractionTiresAdvised = Percentage(tractionTiresAdvisedCount,count),
                PercentTractionTiresRequired = Percentage(tractionTiresRequiredCount,count),
                PercentTrafficDelayed = Percentage(trafficDelayedCount,count),
                PercentTrafficDelayedForAvalancheControl = Percentage(trafficDealyedForAvalancheControlCount,count),
                PercentTrafficStoppedForAvalancheControl = Percentage(trafficStoppedForAvalancheControlCount,count),
                
            };

            return roadConditionSummaryViewModel;
        }

        public ViewResult RangeAnalysis()
        {
            var viewModel = new RoadConditionRangeAnalysisViewModel
            {
                Month = DateTime.Today.ToString("MMMM"),
                Day = 1,
                Range = 5,
                Summary = new RoadConditionSummaryViewModel
                {
                    PercentChainsRequiredAllVehicles = 0,
                    PercentChainsRequiredExceptAllWheelDrive = 0,
                    PercentPassClosed = 0,
                    PercentTractionTiresAdvised = 0,
                    PercentTractionTiresRequired = 0,
                    PercentTrafficDelayed = 0,
                    PercentTrafficDelayedForAvalancheControl = 0,
                    PercentTrafficStoppedForAvalancheControl = 0,
                }
            };

            return View(viewModel);
        }

        private double Percentage(int sum, int count)
        {
            if (count == 0)
                return 0;

            var result=  (double)sum/(double)count*100;

            return result;
        }
    }
}

tempestas_mons.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="http://cdn.kendostatic.com/2014.2.716/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://cdn.kendostatic.com/2014.2.716/styles/kendo.default.min.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="http://cdn.kendostatic.com/2014.2.716/js/angular.min.js"></script>
    <script src="http://cdn.kendostatic.com/2014.2.716/js/kendo.all.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tempestas Mons", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Road Conditions", "Index", "RoadCondition")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
 
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>